### ISSUE TITLE
Allow using multiple QubitStateVector operations if acting on different wires

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#1150]
**Context**

PennyLane allows a single state preparation to be included in a quantum function. Any state preparation that is not the first in the circuit, will raise a `DeviceError`.

```python
import pennylane as qml
import numpy as np

x = np.array([1,0])

dev = qml.device('default.qubit', wires=2)

@qml.qnode(dev)
def prepare_state(x):

    qml.QubitStateVector(x, wires=0)
    return qml.state()

prepare_state(x)
```
```
tensor([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j], requires_grad=True)
```

At times, multiple state preparations could be used in a circuit. An example is when the state preparations are at the beginning of the circuit and there are no shared wires that they act on.

This is, however, incompatible with how PennyLane handles state preparations at the moment:
```python
import pennylane as qml
import numpy as np

x1 = np.array([1,0])
x2 = np.array([0,1])

dev = qml.device('default.qubit', wires=2)

@qml.qnode(dev)
def prepare_state(x1, x2):

    qml.QubitStateVector(x1, wires=0)
    qml.QubitStateVector(x2, wires=1)
    return qml.state()

prepare_state(x1, x2)
```
```
DeviceError: Operation QubitStateVector cannot be used after other Operations have already been applied on a default.qubit.autograd device.
```
**New feature**

* Allow `QubitStateVector` to be applied more than once in a quantum function, if:
    a) no `QubitStateVector` is applied after an operation that is not a state preparation and
    b) every wire is acted on by a state preparation at most once

*Note*: when using several `QubitStateVector`s to prepare a state, each array passed to  `QubitStateVector` should be normalized.

**Comment by co9olguy** [comment]
With this one, we should be a bit careful, because doing those checks might require us to create part of the circuit graph, which may increase overhead.

**Comment by josh146** [comment]
We could take the middle ground, and only check it on the tape.

So allow
```python
qml.QubitStateVector(..., wires=0)
qml.QubitStateVector(..., wires=1)
qml.RX(0.3, wires=0)
```

but disallow

```python
qml.QubitStateVector(..., wires=0)
qml.RX(0.3, wires=0)
qml.QubitStateVector(..., wires=1)
```

**Comment by sassan72** [comment]
has problem been fixed with amplitude embedding?

**Comment by mariaschuld** [comment]
Hey @sassan72, no, unfortunately `AmplitudeEmbedding` calls `QubitStateVector`, so the same problems persist. However, another template, [MottonenStatePreparation](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.templates.state_preparations.MottonenStatePreparation.html) defines a circuit for `AmplitudeEmbedding` which can be applied anywhere. The circuit is quite long, but for now it could help as a quickfix?

Maybe interesting to know, if a device does not know how to implement `QubitStateVector`, then it actually calls that circuit instead - so the result should be the same.

**Comment by sassan72** [comment]
thanks a lot. No problem. I think Mottonen state preparation is better to work with. As you said, i can use it anywhere in the circuit.

**Comment by dwierichs** [comment]
While it's easy to allow the first operations in a tape to all be `QubitStateVector`, realizing all `QubitStateVector` applications after the very first one will be rather costly, compared to the manual tensor product: For each following application of a state vector, the reduced state on the remaining wires has to be extracted and the product state needs to be computed.

I think that for the requested case it will be _much_ easier to manually prepare the product state in the beginning and to pass it to `QubitStateVector` afterwards.
A utility could be provided, allowing for multiple state vector and wire label inputs, and computing the correct tensor product from that information (basically a combination of `qml.math.kron` and `qml.math.expand_matrix`):
```python
state = qml.math.product_state([state0, state1, ...], [wires0, wires1,...])
...
qml.QubitStateVector(state, wires=all_wires)
```

**Comment by dwierichs** [comment]
@trbromley Could close this issue, multiple `QubitStateVector`s are supported by now using their decomposition.

**Comment by albertnieto** [comment]
> @trbromley Could close this issue, multiple `QubitStateVector`s are supported by now using their decomposition.

How would that be? I'm facing this issue right now.

**Comment by dwierichs** [comment]
Hi @albertnieto, that's unfortunate to hear! Could you provide a minimal example of the issue you're facing? The examples above, and even executing operations before one of the `QubitStateVector` seems to work for me on the current master branch.

**Comment by trbromley** [comment]
@albertnieto - also information on which version of PennyLane you are using would be useful.

**Comment by astralcai** [comment]
![](https://media.tenor.com/TigFWS1gf50AAAAM/2000anos-depois.gif)

`QubitStateVector` is now deprecated, and with `StatePrep`, the following code works on latest PL.
```python
import pennylane as qml
import numpy as np

x1 = np.array([1,0])
x2 = np.array([0,1])

dev = qml.device('default.qubit', wires=2)

@qml.qnode(dev)
def prepare_state(x1, x2):

    qml.StatePrep(x1, wires=0)
    qml.StatePrep(x2, wires=1)
    return qml.state()
```
```pycon
>>> prepare_state(x1, x2)
array([6.123234e-17+0.j, 1.000000e+00+0.j, 0.000000e+00+0.j,
       0.000000e+00+0.j])
```
